### ISSUE TITLE
Session/Processlauncher must specify at least one argument for '...' parameter

### ISSUE THREAD

**Issue by fedya** [papyros/papyros-shell#140]
Trying to build papyros-shell from developmet branch

[ 22%] Building CXX object session/CMakeFiles/papyros-session.dir/processlauncher.cpp.o
/home/omv/papyros-shell/BUILD/papyros-shell-0.0.5-20150709/session/processlauncher.cpp:90:21: error: must specify at least one argument for '...' parameter of variadic macro [-Werror,-Wgnu-zero-variadic-macro-arguments]
    qCDebug(LAUNCHER) << "Registered" << interfaceName << "D-Bus interface";
                    ^
/usr/include/qt5/QtCore/qloggingcategory.h:117:9: note: macro 'qCDebug' defined here
# define qCDebug(category, ...) \

```
    ^
```

/home/omv/papyros-shell/BUILD/papyros-shell-0.0.5-20150709/session/processlauncher.cpp:96:21: error: must specify at least one argument for '...' parameter of variadic macro [-Werror,-Wgnu-zero-variadic-macro-arguments]
    qCDebug(LAUNCHER) << "Terminate applications";
                    ^
/usr/include/qt5/QtCore/qloggingcategory.h:117:9: note: macro 'qCDebug' defined here
# define qCDebug(category, ...) \

```
    ^
```

/home/omv/papyros-shell/BUILD/papyros-shell-0.0.5-20150709/session/processlauncher.cpp:108:25: error: must specify at least one argument for '...' parameter of variadic macro [-Werror,-Wgnu-zero-variadic-macro-arguments]
        qCDebug(LAUNCHER) << "Terminating application from" << fileName << "with pid" << process->pid();
                        ^
/usr/include/qt5/QtCore/qloggingcategory.h:117:9: note: macro 'qCDebug' defined here
# define qCDebug(category, ...) \

```
    ^
```

/home/omv/papyros-shell/BUILD/papyros-shell-0.0.5-20150709/session/processlauncher.cpp:124:27: error: must specify at least one argument for '...' parameter of variadic macro [-Werror,-Wgnu-zero-variadic-macro-arguments]
        qCWarning(LAUNCHER) << "No desktop entry found for" << appId;
                          ^
/usr/include/qt5/QtCore/qloggingcategory.h:123:9: note: macro 'qCWarning' defined here
# define qCWarning(category, ...) \

```
    ^
```

/home/omv/papyros-shell/BUILD/papyros-shell-0.0.5-20150709/session/processlauncher.cpp:135:27: error: must specify at least one argument for '...' parameter of variadic macro [-Werror,-Wgnu-zero-variadic-macro-arguments]
        qCWarning(LAUNCHER) << "Failed to open desktop file" << fileName;
                          ^
/usr/include/qt5/QtCore/qloggingcategory.h:123:9: note: macro 'qCWarning' defined here
# define qCWarning(category, ...) \

```
    ^
```

/home/omv/papyros-shell/BUILD/papyros-shell-0.0.5-20150709/session/processlauncher.cpp:150:21: error: must specify at least one argument for '...' parameter of variadic macro [-Werror,-Wgnu-zero-variadic-macro-arguments]
    qCDebug(LAUNCHER) << "Closing application for" << fileName;
                    ^
/usr/include/qt5/QtCore/qloggingcategory.h:117:9: note: macro 'qCDebug' defined here
# define qCDebug(category, ...) \

```
    ^
```

/home/omv/papyros-shell/BUILD/papyros-shell-0.0.5-20150709/session/processlauncher.cpp:220:25: error: must specify at least one argument for '...' parameter of variadic macro [-Werror,-Wgnu-zero-variadic-macro-arguments]
        qCDebug(LAUNCHER) << "Application for" << fileName << "finished with exit code" << exitCode;
                        ^
/usr/include/qt5/QtCore/qloggingcategory.h:117:9: note: macro 'qCDebug' defined here
# define qCDebug(category, ...) \

```
    ^
```

**Comment by ricardomv** [comment]
Can you provide more details?  What distro do you use what commands did you run to build?

**Comment by iBelieve** [comment]
Papyros shell correctly compiles with GreenIsland 0.6 (we're building nightly package sfor Arch). Because this is several months old, I'm going to close this ticket, but if you're still having issues, please feel free to reopen it again.
