### ISSUE TITLE
linker error on opensuse

### ISSUE THREAD

**Issue by progwolff** [papyros/papyros-shell#138]
Trying to compile on opensuse 13.2 with Qt5.5 I get the following linker errors:

```
Linking CXX shared library libpapyrosdesktop.so
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: warning: type and size of dynamic symbol `qt_version_tag@@Qt_5.5' are not defined
CMakeFiles/papyrosdesktop.dir/desktop/desktopfile.cpp.o: In function `DesktopFile::load()':
desktopfile.cpp:(.text+0x794): undefined reference to `XdgDesktopFileCache::getFile(QString const&)'
CMakeFiles/papyrosdesktop.dir/desktop/desktopfile.cpp.o: In function `DesktopFile::iconName() const':
desktopfile.cpp:(.text+0x862): undefined reference to `XdgDesktopFile::iconName() const'
CMakeFiles/papyrosdesktop.dir/desktop/desktopfile.cpp.o: In function `DesktopFile::isValid() const':
desktopfile.cpp:(.text+0x979): undefined reference to `XdgDesktopFile::isValid() const'
CMakeFiles/papyrosdesktop.dir/desktop/desktopfile.cpp.o: In function `DesktopFile::isShown(QString const&) const':
desktopfile.cpp:(.text+0x9b6): undefined reference to `XdgDesktopFile::isShown(QString const&) const'
CMakeFiles/papyrosdesktop.dir/desktop/desktopfile.cpp.o: In function `XdgDesktopFile::name() const':
desktopfile.cpp:(.text._ZNK14XdgDesktopFile4nameEv[_ZNK14XdgDesktopFile4nameEv]+0x43): undefined reference to `XdgDesktopFile::localizedValue(QString const&, QVariant const&) const'
CMakeFiles/papyrosdesktop.dir/desktop/desktopfile.cpp.o: In function `XdgDesktopFile::comment() const':
desktopfile.cpp:(.text._ZNK14XdgDesktopFile7commentEv[_ZNK14XdgDesktopFile7commentEv]+0x43): undefined reference to `XdgDesktopFile::localizedValue(QString const&, QVariant const&) const'
collect2: error: ld returned 1 exit status
```

not sure if this has to to with papyros or libqtxdg...

edit: setting QTXDG_LIBRARIES to a fixed location solves this issue, but this can't be the real solution...

**Comment by 29jm** [comment]
Could you try to to apply the commits from PR #109 to your local repo, see if it works? It seems related.

**Comment by IdrissDimson** [comment]
agreed

**Comment by progwolff** [comment]
You are right, this solves the issue.

**Comment by ricardomv** [comment]
I merged the pull request should be fixed in develop too.
