### ISSUE TITLE
build issue with greenisland git

### ISSUE THREAD

**Issue by SolarAquarion** [papyros/papyros-shell#166]
[ 18%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/notifications/notificationserver.cpp.o
[ 20%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/mpris/mprisconnection.cpp.o
[ 22%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/mpris/mpris2player.cpp.o
[ 24%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/mixer/sound.cpp.o
[ 26%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/mixer/pulseaudiomixer.cpp.o
[ 28%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/mixer/alsamixer.cpp.o
[ 30%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/launcher/launchermodel.cpp.o
/tmp/yaourt-tmp-solaraquarion/aur-papyros-shell-git/src/papyros-shell-git/modules/Papyros/Desktop/launcher/launchermodel.cpp:34:42: fatal error: GreenIsland/ApplicationManager: No such file or directory
compilation terminated.
modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/build.make:278: recipe for target 'modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/launcher/launchermodel.cpp.o' failed
make[2]: **\* [modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/launcher/launchermodel.cpp.o] Error 1
CMakeFiles/Makefile2:362: recipe for target 'modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/all' failed
make[1]: **\* [modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by cptn-cosmo** [comment]
I have the same issue:

/tmp/yaourt-tmp-dawnson/aur-papyros-shell-git/src/papyros-shell-git/modules/Papyros/Desktop/launcher/launchermodel.cpp:34:42: fatal error: GreenIsland/ApplicationManager: No such file or directory
compilation terminated.
modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/build.make:278: recipe for target 'modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/launcher/launchermodel.cpp.o' failed
make[2]: **\* [modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/launcher/launchermodel.cpp.o] Error 1
CMakeFiles/Makefile2:362: recipe for target 'modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/all' failed
make[1]: **\* [modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: **\* [all] Error 2
==> ERROR: A failure occurred in prepare().
    Aborting...
==> ERROR: Makepkg was unable to build papyros-shell-git.

**Comment by XDjackieXD** [comment]
Same issue here (building papyros-shell-git from AUR).

**Comment by iBelieve** [comment]
Papyros currently requires GreenIsland 0.6.

**Comment by teaalltr** [comment]
Yep, it actually does work with 0.6.

**Comment by iBelieve** [comment]
I want to ship each version of Papyros shell on the latest stable version of GreenIsland, which right now is 0.6. Once 0.7 is out, we'll switch to that for the next version of Papyros shell.

**Comment by IdrissDimson** [comment]
^yeah.

**Comment by iBelieve** [comment]
I'm closing this in favor of #180 so we can properly update the code to support GreenIsland 0.7 once it comes out (hopefully in the Papyros shell 0.2 cycle).
